In [1]:
import pandas as pd
import numpy as np

## DataFrames

In [2]:
data = [
    ['Nissan', 'Stanza', 1991, 138, 4, 'MANUAL', 'sedan', 2000],
    ['Hyundai', 'Sonata', 2017, None, 4, 'AUTOMATIC', 'Sedan', 27150],
    ['Lotus', 'Elise', 2010, 218, 4, 'MANUAL', 'convertible', 54990],
    ['GMC', 'Acadia',  2017, 194, 4, 'AUTOMATIC', '4dr SUV', 34450],
    ['Nissan', 'Frontier', 2017, 261, 6, 'MANUAL', 'Pickup', 32340],
]

columns = [
    'Make', 'Model', 'Year', 'Engine HP', 'Engine Cylinders',
    'Transmission Type', 'Vehicle_Style', 'MSRP'
]

In [5]:
df = pd.DataFrame(data, columns=columns)
df

,Make,Model,Year,Engine HP,Engine Cylinders,Transmission Type,Vehicle_Style,MSRP
0,Nissan,Stanza,1991,138.0,4,MANUAL,sedan,2000
1,Hyundai,Sonata,2017,NaN,4,AUTOMATIC,Sedan,27150
2,Lotus,Elise,2010,218.0,4,MANUAL,convertible,54990
3,GMC,Acadia,2017,194.0,4,AUTOMATIC,4dr SUV,34450
4,Nissan,Frontier,2017,261.0,6,MANUAL,Pickup,32340

In [6]:
data = [
    {
        "Make": "Nissan",
        "Model": "Stanza",
        "Year": 1991,
        "Engine HP": 138.0,
        "Engine Cylinders": 4,
        "Transmission Type": "MANUAL",
        "Vehicle_Style": "sedan",
        "MSRP": 2000
    },
    {
        "Make": "Hyundai",
        "Model": "Sonata",
        "Year": 2017,
        "Engine HP": None,
        "Engine Cylinders": 4,
        "Transmission Type": "AUTOMATIC",
        "Vehicle_Style": "Sedan",
        "MSRP": 27150
    },
    {
        "Make": "Lotus",
        "Model": "Elise",
        "Year": 2010,
        "Engine HP": 218.0,
        "Engine Cylinders": 4,
        "Transmission Type": "MANUAL",
        "Vehicle_Style": "convertible",
        "MSRP": 54990
    },
    {
        "Make": "GMC",
        "Model": "Acadia",
        "Year": 2017,
        "Engine HP": 194.0,
        "Engine Cylinders": 4,
        "Transmission Type": "AUTOMATIC",
        "Vehicle_Style": "4dr SUV",
        "MSRP": 34450
    },
    {
        "Make": "Nissan",
        "Model": "Frontier",
        "Year": 2017,
        "Engine HP": 261.0,
        "Engine Cylinders": 6,
        "Transmission Type": "MANUAL",
        "Vehicle_Style": "Pickup",
        "MSRP": 32340
    }
]

In [8]:
df = pd.DataFrame(data)
df

,Make,Model,Year,Engine HP,Engine Cylinders,Transmission Type,Vehicle_Style,MSRP
0,Nissan,Stanza,1991,138.0,4,MANUAL,sedan,2000
1,Hyundai,Sonata,2017,NaN,4,AUTOMATIC,Sedan,27150
2,Lotus,Elise,2010,218.0,4,MANUAL,convertible,54990
3,GMC,Acadia,2017,194.0,4,AUTOMATIC,4dr SUV,34450
4,Nissan,Frontier,2017,261.0,6,MANUAL,Pickup,32340

In [10]:
df.head(n=2)

,Make,Model,Year,Engine HP,Engine Cylinders,Transmission Type,Vehicle_Style,MSRP
0,Nissan,Stanza,1991,138.0,4,MANUAL,sedan,2000
1,Hyundai,Sonata,2017,NaN,4,AUTOMATIC,Sedan,27150

## Series

In [12]:
df.Make

0     Nissan
1    Hyundai
2      Lotus
3        GMC
4     Nissan
Name: Make, dtype: object

In [13]:
df['Make']

0     Nissan
1    Hyundai
2      Lotus
3        GMC
4     Nissan
Name: Make, dtype: object

In [15]:
df[['Make', 'Model', 'MSRP']]

      Make     Model   MSRP
0   Nissan    Stanza   2000
1  Hyundai    Sonata  27150
2    Lotus     Elise  54990
3      GMC    Acadia  34450
4   Nissan  Frontier  32340

In [18]:
# Add Column to DataFrame
df['Id'] = [1, 2, 3, 4, 5]

In [20]:
# Delete from DataFrame
del df['id']

In [23]:
df['Id'] = [10, 20, 30, 40, 50]

In [24]:
df

,Make,Model,Year,Engine HP,Engine Cylinders,Transmission Type,Vehicle_Style,MSRP,Id
0,Nissan,Stanza,1991,138.0,4,MANUAL,sedan,2000,10
1,Hyundai,Sonata,2017,NaN,4,AUTOMATIC,Sedan,27150,20
2,Lotus,Elise,2010,218.0,4,MANUAL,convertible,54990,30
3,GMC,Acadia,2017,194.0,4,AUTOMATIC,4dr SUV,34450,40
4,Nissan,Frontier,2017,261.0,6,MANUAL,Pickup,32340,50

## Index

In [26]:
df.index

RangeIndex(start=0, stop=5, step=1)

In [27]:
df.Make

0     Nissan
1    Hyundai
2      Lotus
3        GMC
4     Nissan
Name: Make, dtype: object

In [28]:
df.Make.index

RangeIndex(start=0, stop=5, step=1)

In [29]:
df.loc[1]

Make                   Hyundai
Model                   Sonata
Year                      2017
Engine HP                  NaN
Engine Cylinders             4
Transmission Type    AUTOMATIC
Vehicle_Style            Sedan
MSRP                     27150
Id                          20
Name: 1, dtype: object

In [30]:
df.loc[[1, 2]]

,Make,Model,Year,Engine HP,Engine Cylinders,Transmission Type,Vehicle_Style,MSRP,Id
1,Hyundai,Sonata,2017,NaN,4,AUTOMATIC,Sedan,27150,20
2,Lotus,Elise,2010,218.0,4,MANUAL,convertible,54990,30

In [31]:
df.index = ['a', 'b', 'c', 'd', 'e']

In [32]:
df

,Make,Model,Year,Engine HP,Engine Cylinders,Transmission Type,Vehicle_Style,MSRP,Id
a,Nissan,Stanza,1991,138.0,4,MANUAL,sedan,2000,10
b,Hyundai,Sonata,2017,NaN,4,AUTOMATIC,Sedan,27150,20
c,Lotus,Elise,2010,218.0,4,MANUAL,convertible,54990,30
d,GMC,Acadia,2017,194.0,4,AUTOMATIC,4dr SUV,34450,40
e,Nissan,Frontier,2017,261.0,6,MANUAL,Pickup,32340,50

## Acessing Elements

In [34]:
df.loc[['a','b']]

,Make,Model,Year,Engine HP,Engine Cylinders,Transmission Type,Vehicle_Style,MSRP,Id
a,Nissan,Stanza,1991,138.0,4,MANUAL,sedan,2000,10
b,Hyundai,Sonata,2017,NaN,4,AUTOMATIC,Sedan,27150,20

In [35]:
df.iloc[[1, 2, 3]]

,Make,Model,Year,Engine HP,Engine Cylinders,Transmission Type,Vehicle_Style,MSRP,Id
b,Hyundai,Sonata,2017,NaN,4,AUTOMATIC,Sedan,27150,20
c,Lotus,Elise,2010,218.0,4,MANUAL,convertible,54990,30
d,GMC,Acadia,2017,194.0,4,AUTOMATIC,4dr SUV,34450,40

In [37]:
df.reset_index()

,index,Make,Model,Year,Engine HP,Engine Cylinders,Transmission Type,Vehicle_Style,MSRP,Id
0,a,Nissan,Stanza,1991,138.0,4,MANUAL,sedan,2000,10
1,b,Hyundai,Sonata,2017,NaN,4,AUTOMATIC,Sedan,27150,20
2,c,Lotus,Elise,2010,218.0,4,MANUAL,convertible,54990,30
3,d,GMC,Acadia,2017,194.0,4,AUTOMATIC,4dr SUV,34450,40
4,e,Nissan,Frontier,2017,261.0,6,MANUAL,Pickup,32340,50

In [38]:
df.reset_index(drop=True)

,Make,Model,Year,Engine HP,Engine Cylinders,Transmission Type,Vehicle_Style,MSRP,Id
0,Nissan,Stanza,1991,138.0,4,MANUAL,sedan,2000,10
1,Hyundai,Sonata,2017,NaN,4,AUTOMATIC,Sedan,27150,20
2,Lotus,Elise,2010,218.0,4,MANUAL,convertible,54990,30
3,GMC,Acadia,2017,194.0,4,AUTOMATIC,4dr SUV,34450,40
4,Nissan,Frontier,2017,261.0,6,MANUAL,Pickup,32340,50

In [39]:
df

,Make,Model,Year,Engine HP,Engine Cylinders,Transmission Type,Vehicle_Style,MSRP,Id
a,Nissan,Stanza,1991,138.0,4,MANUAL,sedan,2000,10
b,Hyundai,Sonata,2017,NaN,4,AUTOMATIC,Sedan,27150,20
c,Lotus,Elise,2010,218.0,4,MANUAL,convertible,54990,30
d,GMC,Acadia,2017,194.0,4,AUTOMATIC,4dr SUV,34450,40
e,Nissan,Frontier,2017,261.0,6,MANUAL,Pickup,32340,50

## ELement-wise operations